name: Install, Build, Deploy

on:
  push:
    branches: [seo, master, prod]
  pull_request:
    branches: 
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Install dependencies
        run: npm i
      - name: Build App
        run: CI=false && npm run build --if-present && git status
        env:
          REACT_APP_STRIPE_KEY: ${{secrets.REACT_APP_STRIPE_KEY}} 
          REACT_APP_RECAPTCHA_SITE_KEY: ${{secrets.REACT_APP_RECAPTCHA_SITE_KEY}} 
      - name: Deploy
        if: ${{github.repository_owner == 'CougarCS' && github.ref == 'refs/heads/prod'}}
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{secrets.FTP_URL}}
          ftp-username: ${{secrets.FTP_USERNAME}}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build
