name: Install, Build, Deploy

on:
  push:
    branches:
      - prod
jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Install dependencies
        run: npm i
      - name: Build App
        run: CI=false && npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Production files
          path: build
      - name: Deploy
        run: echo 'Deploying to prod...'
