name: Build and Push

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build the app
      - run: CI=false && npm run build
