name: Build and Push

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{matrix.node.version}}
      - name: Install dependencies
        run: npm ci
      - name: Build App
        run: CI=false && npm run build --if-present
